baseURL = "https://shinkirou-dev.github.io/blog/"
locale = "en-us"
title = "A dev's tale"
theme = "hugo-bearblog"

[params]
bio = "I build things and watch what happens."
description = "Software engineer. Thinking out loud."

[menu]
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 2